package com.tmb.enums;

public enum ConfigProperties {

    URL,
    OVERRIDEREPORTS,
    PASSEDSTEPSSCREENSHOT,
    FAILEDSTEPSSCREENSHOT,
    SKIPEDSTEPSSCREENSHOT,
    RETRYFAILEDTESTS,
    BROWSER;
}
